#!/usr/bin/env bash

if ! command -v stow &> /dev/null
then
    echo "stow command not found, install using 'brew install stow'"
    exit
fi

stow -D alacritty
stow -D composer
stow -D git
stow -D homebrew
stow -D jetbrains
stow -D karabiner
stow -D nvim
stow -D skhd
stow -D yabai
stow -D zsh
stow -D tmux
stow -D lldb
stow -D asdf
